/* Dove elenchi le action */

const ADD_TODO = 'ADD_TODO';
const EDIT_TODO = 'EDIT_TODO';
const DEL_TODO = 'DEL_TODO';
const MARK_TODO = 'MARK_TODO';
const UPDATE_TEXT = 'UPDATE_TEXT';
const MOD_TEXT = 'MOD_TEXT';

const ASYNC_MARK_TODO = 'ASYNC_MARK_TODO';
const ASYNC_ADD_TODO = 'ASYNC_ADD_TODO';
const ASYNC_EDIT_TODO = 'ASYNC_EDIT_TODO';
const ASYNC_DEL_TODO = 'ASYNC_DEL_TODO';
const ASYNC_UPDATE_TEXT = 'ASYNC_UPDATE_TEXT';
const ASYNC_MOD_TEXT = 'ASYNC_MOD_TEXT';

export {
    ADD_TODO,
    EDIT_TODO,
    DEL_TODO,
    MARK_TODO,
    UPDATE_TEXT,
    MOD_TEXT,
    ASYNC_MARK_TODO,
    ASYNC_ADD_TODO,
    ASYNC_EDIT_TODO,
    ASYNC_DEL_TODO,
    ASYNC_UPDATE_TEXT,
    ASYNC_MOD_TEXT,
};
